require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BoughtCardsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # BoughtCard. As you add validations to BoughtCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoughtCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bought_cards as @bought_cards" do
      bought_card = BoughtCard.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bought_cards)).to eq([bought_card])
    end
  end

  describe "GET show" do
    it "assigns the requested bought_card as @bought_card" do
      bought_card = BoughtCard.create! valid_attributes
      get :show, {:id => bought_card.to_param}, valid_session
      expect(assigns(:bought_card)).to eq(bought_card)
    end
  end

  describe "GET new" do
    it "assigns a new bought_card as @bought_card" do
      get :new, {}, valid_session
      expect(assigns(:bought_card)).to be_a_new(BoughtCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested bought_card as @bought_card" do
      bought_card = BoughtCard.create! valid_attributes
      get :edit, {:id => bought_card.to_param}, valid_session
      expect(assigns(:bought_card)).to eq(bought_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoughtCard" do
        expect {
          post :create, {:bought_card => valid_attributes}, valid_session
        }.to change(BoughtCard, :count).by(1)
      end

      it "assigns a newly created bought_card as @bought_card" do
        post :create, {:bought_card => valid_attributes}, valid_session
        expect(assigns(:bought_card)).to be_a(BoughtCard)
        expect(assigns(:bought_card)).to be_persisted
      end

      it "redirects to the created bought_card" do
        post :create, {:bought_card => valid_attributes}, valid_session
        expect(response).to redirect_to(BoughtCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bought_card as @bought_card" do
        post :create, {:bought_card => invalid_attributes}, valid_session
        expect(assigns(:bought_card)).to be_a_new(BoughtCard)
      end

      it "re-renders the 'new' template" do
        post :create, {:bought_card => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bought_card" do
        bought_card = BoughtCard.create! valid_attributes
        put :update, {:id => bought_card.to_param, :bought_card => new_attributes}, valid_session
        bought_card.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bought_card as @bought_card" do
        bought_card = BoughtCard.create! valid_attributes
        put :update, {:id => bought_card.to_param, :bought_card => valid_attributes}, valid_session
        expect(assigns(:bought_card)).to eq(bought_card)
      end

      it "redirects to the bought_card" do
        bought_card = BoughtCard.create! valid_attributes
        put :update, {:id => bought_card.to_param, :bought_card => valid_attributes}, valid_session
        expect(response).to redirect_to(bought_card)
      end
    end

    describe "with invalid params" do
      it "assigns the bought_card as @bought_card" do
        bought_card = BoughtCard.create! valid_attributes
        put :update, {:id => bought_card.to_param, :bought_card => invalid_attributes}, valid_session
        expect(assigns(:bought_card)).to eq(bought_card)
      end

      it "re-renders the 'edit' template" do
        bought_card = BoughtCard.create! valid_attributes
        put :update, {:id => bought_card.to_param, :bought_card => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bought_card" do
      bought_card = BoughtCard.create! valid_attributes
      expect {
        delete :destroy, {:id => bought_card.to_param}, valid_session
      }.to change(BoughtCard, :count).by(-1)
    end

    it "redirects to the bought_cards list" do
      bought_card = BoughtCard.create! valid_attributes
      delete :destroy, {:id => bought_card.to_param}, valid_session
      expect(response).to redirect_to(bought_cards_url)
    end
  end

end
